text = "Embark";
width = BUTTON_WIDTH;
height = BUTTON_HEIGHT;
text_color = BUTTON_TEXT_COLOR;
sprite = s_button;
action = goto_r_game;
enabled = true;
disabled_message = "Selected a position on the map before continuing";
sound = so_buttonn_embark;
