part_particles_clear(glb_particle_dust_black);
part_particles_clear(glb_particle_dust_white);
part_emitter_stream(glb_part_system_black, glb_dust_emitter_black, glb_particle_dust_black, 0);
part_emitter_stream(glb_part_system_white, glb_dust_emitter_white, glb_particle_dust_white, 0);
